package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.AdminBean;
import kevin.tm.dao.model.AdminBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface AdminBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int countByExample(AdminBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByExample(AdminBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insert(AdminBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insertSelective(AdminBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    List<AdminBean> selectByExample(AdminBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    AdminBean selectByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") AdminBean record,
	    @Param("example") AdminBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExample(@Param("record") AdminBean record,
	    @Param("example") AdminBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKeySelective(AdminBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Admin
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKey(AdminBean record);

    /**
     * 分页全查询
     * 
     * @param start
     *            开始位置，0开始
     * @param limit
     *            查询条数限制
     * @return
     */
    @Select("SELECT TOP(#{limit}) * FROM [Admin] WHERE [LoginId] NOT IN (SELECT TOP(#{start}) [LoginId] FROM [Admin])")
    List<AdminBean> selectByPage(@Param("start") int start,
	    @Param("limit") int limit);
}