package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.AdminBean;
import kevin.tm.dao.model.BusBean;
import kevin.tm.dao.model.BusBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface BusBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int countByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insert(BusBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insertSelective(BusBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    List<BusBean> selectByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    BusBean selectByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") BusBean record,
	    @Param("example") BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExample(@Param("record") BusBean record,
	    @Param("example") BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKeySelective(BusBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Bus
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKey(BusBean record);

    /**
     * 分页全查询
     * 
     * @param start
     *            开始位置，0开始
     * @param limit
     *            查询条数限制
     * @return
     */
    @Select("SELECT TOP(#{limit}) * FROM [Bus] WHERE [VehicleNo] NOT IN (SELECT TOP(#{start}) [VehicleNo] FROM [Bus])")
    List<AdminBean> selectByPage(@Param("start") int start,
	    @Param("limit") int limit);
}