package kevin.tm.dao;

import java.util.List;
import kevin.tm.model.BusBean;
import kevin.tm.model.BusBeanExample;
import org.apache.ibatis.annotations.Param;

public interface BusBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int countByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int deleteByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int deleteByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int insert(BusBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int insertSelective(BusBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    List<BusBean> selectByExample(BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    BusBean selectByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int updateByExampleSelective(@Param("record") BusBean record, @Param("example") BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int updateByExample(@Param("record") BusBean record, @Param("example") BusBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int updateByPrimaryKeySelective(BusBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bus
     *
     * @mbggenerated Mon Mar 03 17:46:15 CST 2014
     */
    int updateByPrimaryKey(BusBean record);
}