package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.Businfo;
import kevin.tm.dao.model.BusinfoExample;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface BusinfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table businfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(BusinfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table businfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Businfo> selectByExample(BusinfoExample example);

    @Select("select * from businfo")
    List<Businfo> selectByPage(RowBounds rowBounds);

}