package kevin.tm.dao;

import java.util.List;
import kevin.tm.model.RouteScheduleBean;
import kevin.tm.model.RouteScheduleBeanExample;
import org.apache.ibatis.annotations.Param;

public interface RouteScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int countByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int deleteByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int deleteByPrimaryKey(Integer scheduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int insert(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int insertSelective(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    List<RouteScheduleBean> selectByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    RouteScheduleBean selectByPrimaryKey(Integer scheduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") RouteScheduleBean record, @Param("example") RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int updateByExample(@Param("record") RouteScheduleBean record, @Param("example") RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int updateByPrimaryKeySelective(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RouteSchedule
     *
     * @mbggenerated Sun Mar 02 22:36:18 CST 2014
     */
    int updateByPrimaryKey(RouteScheduleBean record);
}