package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.RouteBean;
import kevin.tm.dao.model.RouteBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface RouteBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int countByExample(RouteBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByExample(RouteBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByPrimaryKey(Integer routeid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insert(RouteBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insertSelective(RouteBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    List<RouteBean> selectByExample(RouteBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    RouteBean selectByPrimaryKey(Integer routeid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") RouteBean record,
	    @Param("example") RouteBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExample(@Param("record") RouteBean record,
	    @Param("example") RouteBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKeySelective(RouteBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Route
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKey(RouteBean record);

    /**
     * 分页全查询
     * 
     * @param start
     *            开始位置，0开始
     * @param limit
     *            查询条数限制
     * @return
     */
    @Select("SELECT TOP(#{limit}) * FROM [Route] WHERE [RouteId] NOT IN (SELECT TOP(#{start}) [RouteId] FROM [Route])")
    List<RouteBean> selectByPage(@Param("start") int start,
	    @Param("limit") int limit);
}