package kevin.tm.dao;

import java.util.List;
import kevin.tm.dao.model.Routeinfo;
import kevin.tm.dao.model.RouteinfoExample;
import org.apache.ibatis.annotations.Param;

public interface RouteinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(RouteinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int deleteByExample(RouteinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insert(Routeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insertSelective(Routeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Routeinfo> selectByExample(RouteinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") Routeinfo record, @Param("example") RouteinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routeinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExample(@Param("record") Routeinfo record, @Param("example") RouteinfoExample example);
}