package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.AdminBean;
import kevin.tm.dao.model.RouteScheduleBean;
import kevin.tm.dao.model.RouteScheduleBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface RouteScheduleBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int countByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByPrimaryKey(Integer scheduleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insert(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insertSelective(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    List<RouteScheduleBean> selectByExample(RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    RouteScheduleBean selectByPrimaryKey(Integer scheduleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") RouteScheduleBean record,
	    @Param("example") RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExample(@Param("record") RouteScheduleBean record,
	    @Param("example") RouteScheduleBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKeySelective(RouteScheduleBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table RouteSchedule
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKey(RouteScheduleBean record);

    /**
     * 分页全查询
     * 
     * @param start
     *            开始位置，0开始
     * @param limit
     *            查询条数限制
     * @return
     */
    @Select("SELECT TOP(#{limit}) * FROM [RouteSchedule] WHERE [ScheduleId] NOT IN (SELECT TOP(#{start}) [ScheduleId] FROM [RouteSchedule])")
    List<AdminBean> selectByPage(@Param("start") int start,
	    @Param("limit") int limit);
}