package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.Routeinfo;
import kevin.tm.dao.model.RouteinfoExample;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface RouteinfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table routeinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(RouteinfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table routeinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Routeinfo> selectByExample(RouteinfoExample example);

    @Select("select * from routeinfo")
    List<Routeinfo> selectByPage(RowBounds rowBounds);
}