package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.Scheduleinfo;
import kevin.tm.dao.model.ScheduleinfoExample;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface ScheduleinfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scheduleinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scheduleinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Scheduleinfo> selectByExample(ScheduleinfoExample example);

    @Select("select * from scheduleinfo")
    List<Scheduleinfo> selectByPage(RowBounds rowBounds);
}