package kevin.tm.dao;

import java.util.List;

import javax.annotation.PostConstruct;

import kevin.tm.dao.model.Scheduleinfo;
import kevin.tm.dao.model.ScheduleinfoExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface ScheduleinfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scheduleinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scheduleinfo
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Scheduleinfo> selectByExample(ScheduleinfoExample example);

    @Select("select * from scheduleinfo where ${searchClause}")
    List<Scheduleinfo> selectByPage(RowBounds rowBounds,@Param("searchClause")String searchClause);
    @Select("SELECT * FROM scheduleinfo WHERE ${searchClause} and DATE_SUB( starttime, INTERVAL '00:20:00' HOUR_SECOND ) > now() " +
    		"AND scheduleid NOT IN " +
    		"( SELECT ticketscheduleid FROM ticket GROUP BY ticketscheduleid " +
    		"HAVING count(*) >= ( SELECT seatcount FROM bus WHERE busid = schedulebusid ))")
    List<Scheduleinfo> selectByPageBeforeNow(RowBounds rowBounds,@Param("searchClause")String searchClause);
    
    @Select("select * from scheduleinfo where scheduleid = #{scheduleid}")
    Scheduleinfo selectByScheduleId(@Param("scheduleid")Integer scheduleid);
}