package kevin.tm.dao;

import java.util.List;
import kevin.tm.dao.model.Scheduleinfo;
import kevin.tm.dao.model.ScheduleinfoExample;
import org.apache.ibatis.annotations.Param;

public interface ScheduleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int deleteByExample(ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insert(Scheduleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insertSelective(Scheduleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<Scheduleinfo> selectByExample(ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") Scheduleinfo record, @Param("example") ScheduleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduleinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExample(@Param("record") Scheduleinfo record, @Param("example") ScheduleinfoExample example);
}