package kevin.tm.dao;

import java.util.List;
import kevin.tm.dao.model.StationBean;
import kevin.tm.dao.model.StationBeanExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface StationBeanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int countByExample(StationBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int deleteByExample(StationBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int deleteByPrimaryKey(Integer stationid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int insert(StationBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int insertSelective(StationBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	List<StationBean> selectByExample(StationBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	StationBean selectByPrimaryKey(Integer stationid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int updateByExampleSelective(@Param("record") StationBean record,
			@Param("example") StationBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int updateByExample(@Param("record") StationBean record,
			@Param("example") StationBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int updateByPrimaryKeySelective(StationBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table station
	 * @mbggenerated  Tue Mar 11 14:47:47 CST 2014
	 */
	int updateByPrimaryKey(StationBean record);
	
	@Select("select * from station")
	List<StationBean> selectByPage(RowBounds rowBounds);
}
