package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.TicketBean;
import kevin.tm.dao.model.TicketBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TicketBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int countByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int deleteByPrimaryKey(Integer ticketid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insert(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int insertSelective(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    List<TicketBean> selectByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    TicketBean selectByPrimaryKey(Integer ticketid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") TicketBean record,
	    @Param("example") TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByExample(@Param("record") TicketBean record,
	    @Param("example") TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKeySelective(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table Ticket
     * 
     * @mbggenerated Mon Mar 03 20:49:21 CST 2014
     */
    int updateByPrimaryKey(TicketBean record);

    /**
     * 分页全查询
     * 
     * @param start
     *            开始位置，0开始
     * @param limit
     *            查询条数限制
     * @return
     */
    @Select("SELECT TOP(#{limit}) * FROM [Ticket] WHERE [TicketId] NOT IN (SELECT TOP(#{start}) [TicketId] FROM [Ticket])")
    List<TicketBean> selectByPage(@Param("start") int start,
	    @Param("limit") int limit);
}