package kevin.tm.dao;

import java.util.List;

import kevin.tm.dao.model.TicketBean;
import kevin.tm.dao.model.TicketBeanExample;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface TicketBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int countByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int deleteByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int deleteByPrimaryKey(Integer ticketid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insert(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int insertSelective(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    List<TicketBean> selectByExample(TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    TicketBean selectByPrimaryKey(Integer ticketid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") TicketBean record,
	    @Param("example") TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByExample(@Param("record") TicketBean record,
	    @Param("example") TicketBeanExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByPrimaryKeySelective(TicketBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ticket
     * 
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    int updateByPrimaryKey(TicketBean record);

    @Select("select * from ticket")
    List<TicketBean> selectByPage(RowBounds rowBounds);
    
    @Select("select (sum1.seatcount-sum2.sellcount) as remaincount from" +
    		"(select seatcount from bus where busid in (select schedulebusid from routeschedule where scheduleid = #{scheduleid}) ) sum1,"+
    		"(select count(*) as sellcount from ticket where ticketscheduleid = #{scheduleid}) sum2")
    int countRemainSeatBySchid(@Param("scheduleid")int scheduleid);
    //查询该班次售出座位列表
    @Select("select seatno from ticketinfo where ticketscheduleid = #{scheduleid}")
    List<String> getSeatList(@Param("scheduleid")int scheduleid);
    //查询该班次座位总数
    @Select("select seatcount from bus where busid in (select schedulebusid from routeschedule where scheduleid = #{scheduleid})")
    int getTotalSeats(@Param("scheduleid")int scheduleid);
    @Select("update ticket set checked=true where ticketid=${ticketid}")
    int updateCheck(@Param("ticketid")int ticketid);
}