package kevin.tm.model;

import java.util.ArrayList;
import java.util.List;

public class BusBeanExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public BusBeanExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andVehiclenoIsNull() {
			addCriterion("VehicleNo is null");
			return (Criteria) this;
		}

		public Criteria andVehiclenoIsNotNull() {
			addCriterion("VehicleNo is not null");
			return (Criteria) this;
		}

		public Criteria andVehiclenoEqualTo(String value) {
			addCriterion("VehicleNo =", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoNotEqualTo(String value) {
			addCriterion("VehicleNo <>", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoGreaterThan(String value) {
			addCriterion("VehicleNo >", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoGreaterThanOrEqualTo(String value) {
			addCriterion("VehicleNo >=", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoLessThan(String value) {
			addCriterion("VehicleNo <", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoLessThanOrEqualTo(String value) {
			addCriterion("VehicleNo <=", value, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoIn(List<String> values) {
			addCriterion("VehicleNo in", values, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoNotIn(List<String> values) {
			addCriterion("VehicleNo not in", values, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoBetween(String value1, String value2) {
			addCriterion("VehicleNo between", value1, value2, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andVehiclenoNotBetween(String value1, String value2) {
			addCriterion("VehicleNo not between", value1, value2, "vehicleno");
			return (Criteria) this;
		}

		public Criteria andDrivernameIsNull() {
			addCriterion("DriverName is null");
			return (Criteria) this;
		}

		public Criteria andDrivernameIsNotNull() {
			addCriterion("DriverName is not null");
			return (Criteria) this;
		}

		public Criteria andDrivernameEqualTo(String value) {
			addCriterion("DriverName =", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameNotEqualTo(String value) {
			addCriterion("DriverName <>", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameGreaterThan(String value) {
			addCriterion("DriverName >", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameGreaterThanOrEqualTo(String value) {
			addCriterion("DriverName >=", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameLessThan(String value) {
			addCriterion("DriverName <", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameLessThanOrEqualTo(String value) {
			addCriterion("DriverName <=", value, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameIn(List<String> values) {
			addCriterion("DriverName in", values, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameNotIn(List<String> values) {
			addCriterion("DriverName not in", values, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameBetween(String value1, String value2) {
			addCriterion("DriverName between", value1, value2, "drivername");
			return (Criteria) this;
		}

		public Criteria andDrivernameNotBetween(String value1, String value2) {
			addCriterion("DriverName not between", value1, value2, "drivername");
			return (Criteria) this;
		}

		public Criteria andSeatcountIsNull() {
			addCriterion("SeatCount is null");
			return (Criteria) this;
		}

		public Criteria andSeatcountIsNotNull() {
			addCriterion("SeatCount is not null");
			return (Criteria) this;
		}

		public Criteria andSeatcountEqualTo(Integer value) {
			addCriterion("SeatCount =", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountNotEqualTo(Integer value) {
			addCriterion("SeatCount <>", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountGreaterThan(Integer value) {
			addCriterion("SeatCount >", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("SeatCount >=", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountLessThan(Integer value) {
			addCriterion("SeatCount <", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountLessThanOrEqualTo(Integer value) {
			addCriterion("SeatCount <=", value, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountIn(List<Integer> values) {
			addCriterion("SeatCount in", values, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountNotIn(List<Integer> values) {
			addCriterion("SeatCount not in", values, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountBetween(Integer value1, Integer value2) {
			addCriterion("SeatCount between", value1, value2, "seatcount");
			return (Criteria) this;
		}

		public Criteria andSeatcountNotBetween(Integer value1, Integer value2) {
			addCriterion("SeatCount not between", value1, value2, "seatcount");
			return (Criteria) this;
		}

		public Criteria andBusstateIsNull() {
			addCriterion("BusState is null");
			return (Criteria) this;
		}

		public Criteria andBusstateIsNotNull() {
			addCriterion("BusState is not null");
			return (Criteria) this;
		}

		public Criteria andBusstateEqualTo(Integer value) {
			addCriterion("BusState =", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateNotEqualTo(Integer value) {
			addCriterion("BusState <>", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateGreaterThan(Integer value) {
			addCriterion("BusState >", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateGreaterThanOrEqualTo(Integer value) {
			addCriterion("BusState >=", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateLessThan(Integer value) {
			addCriterion("BusState <", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateLessThanOrEqualTo(Integer value) {
			addCriterion("BusState <=", value, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateIn(List<Integer> values) {
			addCriterion("BusState in", values, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateNotIn(List<Integer> values) {
			addCriterion("BusState not in", values, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateBetween(Integer value1, Integer value2) {
			addCriterion("BusState between", value1, value2, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstateNotBetween(Integer value1, Integer value2) {
			addCriterion("BusState not between", value1, value2, "busstate");
			return (Criteria) this;
		}

		public Criteria andBusstationidIsNull() {
			addCriterion("BusStationId is null");
			return (Criteria) this;
		}

		public Criteria andBusstationidIsNotNull() {
			addCriterion("BusStationId is not null");
			return (Criteria) this;
		}

		public Criteria andBusstationidEqualTo(Integer value) {
			addCriterion("BusStationId =", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidNotEqualTo(Integer value) {
			addCriterion("BusStationId <>", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidGreaterThan(Integer value) {
			addCriterion("BusStationId >", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidGreaterThanOrEqualTo(Integer value) {
			addCriterion("BusStationId >=", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidLessThan(Integer value) {
			addCriterion("BusStationId <", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidLessThanOrEqualTo(Integer value) {
			addCriterion("BusStationId <=", value, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidIn(List<Integer> values) {
			addCriterion("BusStationId in", values, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidNotIn(List<Integer> values) {
			addCriterion("BusStationId not in", values, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidBetween(Integer value1, Integer value2) {
			addCriterion("BusStationId between", value1, value2, "busstationid");
			return (Criteria) this;
		}

		public Criteria andBusstationidNotBetween(Integer value1, Integer value2) {
			addCriterion("BusStationId not between", value1, value2,
					"busstationid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidIsNull() {
			addCriterion("BusRouteId is null");
			return (Criteria) this;
		}

		public Criteria andBusrouteidIsNotNull() {
			addCriterion("BusRouteId is not null");
			return (Criteria) this;
		}

		public Criteria andBusrouteidEqualTo(Integer value) {
			addCriterion("BusRouteId =", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidNotEqualTo(Integer value) {
			addCriterion("BusRouteId <>", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidGreaterThan(Integer value) {
			addCriterion("BusRouteId >", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidGreaterThanOrEqualTo(Integer value) {
			addCriterion("BusRouteId >=", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidLessThan(Integer value) {
			addCriterion("BusRouteId <", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidLessThanOrEqualTo(Integer value) {
			addCriterion("BusRouteId <=", value, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidIn(List<Integer> values) {
			addCriterion("BusRouteId in", values, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidNotIn(List<Integer> values) {
			addCriterion("BusRouteId not in", values, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidBetween(Integer value1, Integer value2) {
			addCriterion("BusRouteId between", value1, value2, "busrouteid");
			return (Criteria) this;
		}

		public Criteria andBusrouteidNotBetween(Integer value1, Integer value2) {
			addCriterion("BusRouteId not between", value1, value2, "busrouteid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Bus
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Bus
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 02 22:36:18 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}