package kevin.tm.model;

import java.util.Date;

public class RouteScheduleBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.ScheduleId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private Integer scheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.ScheduleRouteId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private Integer schedulerouteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.StartTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.EndTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.ScheduleName
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private String schedulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RouteSchedule.ScheduleVehicleNo
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    private String schedulevehicleno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.ScheduleId
     *
     * @return the value of RouteSchedule.ScheduleId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public Integer getScheduleid() {
        return scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.ScheduleId
     *
     * @param scheduleid the value for RouteSchedule.ScheduleId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setScheduleid(Integer scheduleid) {
        this.scheduleid = scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.ScheduleRouteId
     *
     * @return the value of RouteSchedule.ScheduleRouteId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public Integer getSchedulerouteid() {
        return schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.ScheduleRouteId
     *
     * @param schedulerouteid the value for RouteSchedule.ScheduleRouteId
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setSchedulerouteid(Integer schedulerouteid) {
        this.schedulerouteid = schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.StartTime
     *
     * @return the value of RouteSchedule.StartTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.StartTime
     *
     * @param starttime the value for RouteSchedule.StartTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.EndTime
     *
     * @return the value of RouteSchedule.EndTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.EndTime
     *
     * @param endtime the value for RouteSchedule.EndTime
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.ScheduleName
     *
     * @return the value of RouteSchedule.ScheduleName
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public String getSchedulename() {
        return schedulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.ScheduleName
     *
     * @param schedulename the value for RouteSchedule.ScheduleName
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setSchedulename(String schedulename) {
        this.schedulename = schedulename == null ? null : schedulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RouteSchedule.ScheduleVehicleNo
     *
     * @return the value of RouteSchedule.ScheduleVehicleNo
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public String getSchedulevehicleno() {
        return schedulevehicleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RouteSchedule.ScheduleVehicleNo
     *
     * @param schedulevehicleno the value for RouteSchedule.ScheduleVehicleNo
     *
     * @mbggenerated Mon Mar 03 17:06:52 CST 2014
     */
    public void setSchedulevehicleno(String schedulevehicleno) {
        this.schedulevehicleno = schedulevehicleno == null ? null : schedulevehicleno.trim();
    }
}