package kevin.tm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicketBeanExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public TicketBeanExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTicketidIsNull() {
			addCriterion("TicketId is null");
			return (Criteria) this;
		}

		public Criteria andTicketidIsNotNull() {
			addCriterion("TicketId is not null");
			return (Criteria) this;
		}

		public Criteria andTicketidEqualTo(Integer value) {
			addCriterion("TicketId =", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotEqualTo(Integer value) {
			addCriterion("TicketId <>", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidGreaterThan(Integer value) {
			addCriterion("TicketId >", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidGreaterThanOrEqualTo(Integer value) {
			addCriterion("TicketId >=", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidLessThan(Integer value) {
			addCriterion("TicketId <", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidLessThanOrEqualTo(Integer value) {
			addCriterion("TicketId <=", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidIn(List<Integer> values) {
			addCriterion("TicketId in", values, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotIn(List<Integer> values) {
			addCriterion("TicketId not in", values, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidBetween(Integer value1, Integer value2) {
			addCriterion("TicketId between", value1, value2, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotBetween(Integer value1, Integer value2) {
			addCriterion("TicketId not between", value1, value2, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTickettitleIsNull() {
			addCriterion("TicketTitle is null");
			return (Criteria) this;
		}

		public Criteria andTickettitleIsNotNull() {
			addCriterion("TicketTitle is not null");
			return (Criteria) this;
		}

		public Criteria andTickettitleEqualTo(String value) {
			addCriterion("TicketTitle =", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleNotEqualTo(String value) {
			addCriterion("TicketTitle <>", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleGreaterThan(String value) {
			addCriterion("TicketTitle >", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleGreaterThanOrEqualTo(String value) {
			addCriterion("TicketTitle >=", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleLessThan(String value) {
			addCriterion("TicketTitle <", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleLessThanOrEqualTo(String value) {
			addCriterion("TicketTitle <=", value, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleIn(List<String> values) {
			addCriterion("TicketTitle in", values, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleNotIn(List<String> values) {
			addCriterion("TicketTitle not in", values, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleBetween(String value1, String value2) {
			addCriterion("TicketTitle between", value1, value2, "tickettitle");
			return (Criteria) this;
		}

		public Criteria andTickettitleNotBetween(String value1, String value2) {
			addCriterion("TicketTitle not between", value1, value2,
					"tickettitle");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidIsNull() {
			addCriterion("TicketScheduleId is null");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidIsNotNull() {
			addCriterion("TicketScheduleId is not null");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidEqualTo(Integer value) {
			addCriterion("TicketScheduleId =", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidNotEqualTo(Integer value) {
			addCriterion("TicketScheduleId <>", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidGreaterThan(Integer value) {
			addCriterion("TicketScheduleId >", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidGreaterThanOrEqualTo(Integer value) {
			addCriterion("TicketScheduleId >=", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidLessThan(Integer value) {
			addCriterion("TicketScheduleId <", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidLessThanOrEqualTo(Integer value) {
			addCriterion("TicketScheduleId <=", value, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidIn(List<Integer> values) {
			addCriterion("TicketScheduleId in", values, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidNotIn(List<Integer> values) {
			addCriterion("TicketScheduleId not in", values, "ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidBetween(Integer value1,
				Integer value2) {
			addCriterion("TicketScheduleId between", value1, value2,
					"ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andTicketscheduleidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("TicketScheduleId not between", value1, value2,
					"ticketscheduleid");
			return (Criteria) this;
		}

		public Criteria andSeatnoIsNull() {
			addCriterion("SeatNo is null");
			return (Criteria) this;
		}

		public Criteria andSeatnoIsNotNull() {
			addCriterion("SeatNo is not null");
			return (Criteria) this;
		}

		public Criteria andSeatnoEqualTo(String value) {
			addCriterion("SeatNo =", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoNotEqualTo(String value) {
			addCriterion("SeatNo <>", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoGreaterThan(String value) {
			addCriterion("SeatNo >", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoGreaterThanOrEqualTo(String value) {
			addCriterion("SeatNo >=", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoLessThan(String value) {
			addCriterion("SeatNo <", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoLessThanOrEqualTo(String value) {
			addCriterion("SeatNo <=", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoLike(String value) {
			addCriterion("SeatNo like", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoNotLike(String value) {
			addCriterion("SeatNo not like", value, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoIn(List<String> values) {
			addCriterion("SeatNo in", values, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoNotIn(List<String> values) {
			addCriterion("SeatNo not in", values, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoBetween(String value1, String value2) {
			addCriterion("SeatNo between", value1, value2, "seatno");
			return (Criteria) this;
		}

		public Criteria andSeatnoNotBetween(String value1, String value2) {
			addCriterion("SeatNo not between", value1, value2, "seatno");
			return (Criteria) this;
		}

		public Criteria andCustomernameIsNull() {
			addCriterion("CustomerName is null");
			return (Criteria) this;
		}

		public Criteria andCustomernameIsNotNull() {
			addCriterion("CustomerName is not null");
			return (Criteria) this;
		}

		public Criteria andCustomernameEqualTo(String value) {
			addCriterion("CustomerName =", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameNotEqualTo(String value) {
			addCriterion("CustomerName <>", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameGreaterThan(String value) {
			addCriterion("CustomerName >", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
			addCriterion("CustomerName >=", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameLessThan(String value) {
			addCriterion("CustomerName <", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameLessThanOrEqualTo(String value) {
			addCriterion("CustomerName <=", value, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameIn(List<String> values) {
			addCriterion("CustomerName in", values, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameNotIn(List<String> values) {
			addCriterion("CustomerName not in", values, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameBetween(String value1, String value2) {
			addCriterion("CustomerName between", value1, value2, "customername");
			return (Criteria) this;
		}

		public Criteria andCustomernameNotBetween(String value1, String value2) {
			addCriterion("CustomerName not between", value1, value2,
					"customername");
			return (Criteria) this;
		}

		public Criteria andTicketnoIsNull() {
			addCriterion("TicketNo is null");
			return (Criteria) this;
		}

		public Criteria andTicketnoIsNotNull() {
			addCriterion("TicketNo is not null");
			return (Criteria) this;
		}

		public Criteria andTicketnoEqualTo(String value) {
			addCriterion("TicketNo =", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoNotEqualTo(String value) {
			addCriterion("TicketNo <>", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoGreaterThan(String value) {
			addCriterion("TicketNo >", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoGreaterThanOrEqualTo(String value) {
			addCriterion("TicketNo >=", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoLessThan(String value) {
			addCriterion("TicketNo <", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoLessThanOrEqualTo(String value) {
			addCriterion("TicketNo <=", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoLike(String value) {
			addCriterion("TicketNo like", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoNotLike(String value) {
			addCriterion("TicketNo not like", value, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoIn(List<String> values) {
			addCriterion("TicketNo in", values, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoNotIn(List<String> values) {
			addCriterion("TicketNo not in", values, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoBetween(String value1, String value2) {
			addCriterion("TicketNo between", value1, value2, "ticketno");
			return (Criteria) this;
		}

		public Criteria andTicketnoNotBetween(String value1, String value2) {
			addCriterion("TicketNo not between", value1, value2, "ticketno");
			return (Criteria) this;
		}

		public Criteria andEntrytimeIsNull() {
			addCriterion("EntryTime is null");
			return (Criteria) this;
		}

		public Criteria andEntrytimeIsNotNull() {
			addCriterion("EntryTime is not null");
			return (Criteria) this;
		}

		public Criteria andEntrytimeEqualTo(Date value) {
			addCriterion("EntryTime =", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeNotEqualTo(Date value) {
			addCriterion("EntryTime <>", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeGreaterThan(Date value) {
			addCriterion("EntryTime >", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeGreaterThanOrEqualTo(Date value) {
			addCriterion("EntryTime >=", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeLessThan(Date value) {
			addCriterion("EntryTime <", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeLessThanOrEqualTo(Date value) {
			addCriterion("EntryTime <=", value, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeIn(List<Date> values) {
			addCriterion("EntryTime in", values, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeNotIn(List<Date> values) {
			addCriterion("EntryTime not in", values, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeBetween(Date value1, Date value2) {
			addCriterion("EntryTime between", value1, value2, "entrytime");
			return (Criteria) this;
		}

		public Criteria andEntrytimeNotBetween(Date value1, Date value2) {
			addCriterion("EntryTime not between", value1, value2, "entrytime");
			return (Criteria) this;
		}

		public Criteria andDeadlineIsNull() {
			addCriterion("DeadLine is null");
			return (Criteria) this;
		}

		public Criteria andDeadlineIsNotNull() {
			addCriterion("DeadLine is not null");
			return (Criteria) this;
		}

		public Criteria andDeadlineEqualTo(Date value) {
			addCriterion("DeadLine =", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotEqualTo(Date value) {
			addCriterion("DeadLine <>", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineGreaterThan(Date value) {
			addCriterion("DeadLine >", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
			addCriterion("DeadLine >=", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineLessThan(Date value) {
			addCriterion("DeadLine <", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineLessThanOrEqualTo(Date value) {
			addCriterion("DeadLine <=", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineIn(List<Date> values) {
			addCriterion("DeadLine in", values, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotIn(List<Date> values) {
			addCriterion("DeadLine not in", values, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineBetween(Date value1, Date value2) {
			addCriterion("DeadLine between", value1, value2, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotBetween(Date value1, Date value2) {
			addCriterion("DeadLine not between", value1, value2, "deadline");
			return (Criteria) this;
		}

		public Criteria andCheckedIsNull() {
			addCriterion("Checked is null");
			return (Criteria) this;
		}

		public Criteria andCheckedIsNotNull() {
			addCriterion("Checked is not null");
			return (Criteria) this;
		}

		public Criteria andCheckedEqualTo(Boolean value) {
			addCriterion("Checked =", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedNotEqualTo(Boolean value) {
			addCriterion("Checked <>", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedGreaterThan(Boolean value) {
			addCriterion("Checked >", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("Checked >=", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedLessThan(Boolean value) {
			addCriterion("Checked <", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedLessThanOrEqualTo(Boolean value) {
			addCriterion("Checked <=", value, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedIn(List<Boolean> values) {
			addCriterion("Checked in", values, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedNotIn(List<Boolean> values) {
			addCriterion("Checked not in", values, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedBetween(Boolean value1, Boolean value2) {
			addCriterion("Checked between", value1, value2, "checked");
			return (Criteria) this;
		}

		public Criteria andCheckedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("Checked not between", value1, value2, "checked");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Ticket
	 * @mbggenerated  Mon Mar 03 15:59:33 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ticket
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 02 22:36:18 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}