package kevin.tm.dao.model;

public class Businfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.busid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String vehicleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String drivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.seatcount
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer seatcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.busstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer busstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.busstate
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer busstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businfo.stationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String stationname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.busid
     *
     * @return the value of businfo.busid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getBusid() {
        return busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.busid
     *
     * @param busid the value for businfo.busid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.vehicleno
     *
     * @return the value of businfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getVehicleno() {
        return vehicleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.vehicleno
     *
     * @param vehicleno the value for businfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setVehicleno(String vehicleno) {
        this.vehicleno = vehicleno == null ? null : vehicleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.drivername
     *
     * @return the value of businfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getDrivername() {
        return drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.drivername
     *
     * @param drivername the value for businfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setDrivername(String drivername) {
        this.drivername = drivername == null ? null : drivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.seatcount
     *
     * @return the value of businfo.seatcount
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getSeatcount() {
        return seatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.seatcount
     *
     * @param seatcount the value for businfo.seatcount
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setSeatcount(Integer seatcount) {
        this.seatcount = seatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.busstationid
     *
     * @return the value of businfo.busstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getBusstationid() {
        return busstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.busstationid
     *
     * @param busstationid the value for businfo.busstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setBusstationid(Integer busstationid) {
        this.busstationid = busstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.busstate
     *
     * @return the value of businfo.busstate
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getBusstate() {
        return busstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.busstate
     *
     * @param busstate the value for businfo.busstate
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setBusstate(Integer busstate) {
        this.busstate = busstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businfo.stationname
     *
     * @return the value of businfo.stationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businfo.stationname
     *
     * @param stationname the value for businfo.stationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }
}