package kevin.tm.dao.model;

public class RouteBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer routeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String routename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer startstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer endstationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeid
     *
     * @return the value of route.routeid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeid
     *
     * @param routeid the value for route.routeid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setRouteid(Integer routeid) {
        this.routeid = routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routename
     *
     * @return the value of route.routename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routename
     *
     * @param routename the value for route.routename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startstationid
     *
     * @return the value of route.startstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getStartstationid() {
        return startstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startstationid
     *
     * @param startstationid the value for route.startstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setStartstationid(Integer startstationid) {
        this.startstationid = startstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endstationid
     *
     * @return the value of route.endstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getEndstationid() {
        return endstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endstationid
     *
     * @param endstationid the value for route.endstationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setEndstationid(Integer endstationid) {
        this.endstationid = endstationid;
    }
}