package kevin.tm.dao.model;

public class Routeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.routeid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer routeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String routename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.startstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer startstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.endstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer endstationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String startstationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String endstationname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.routeid
     *
     * @return the value of routeinfo.routeid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.routeid
     *
     * @param routeid the value for routeinfo.routeid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setRouteid(Integer routeid) {
        this.routeid = routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.routename
     *
     * @return the value of routeinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.routename
     *
     * @param routename the value for routeinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.startstationid
     *
     * @return the value of routeinfo.startstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getStartstationid() {
        return startstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.startstationid
     *
     * @param startstationid the value for routeinfo.startstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setStartstationid(Integer startstationid) {
        this.startstationid = startstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.endstationid
     *
     * @return the value of routeinfo.endstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getEndstationid() {
        return endstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.endstationid
     *
     * @param endstationid the value for routeinfo.endstationid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setEndstationid(Integer endstationid) {
        this.endstationid = endstationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.startstationname
     *
     * @return the value of routeinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getStartstationname() {
        return startstationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.startstationname
     *
     * @param startstationname the value for routeinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setStartstationname(String startstationname) {
        this.startstationname = startstationname == null ? null : startstationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeinfo.endstationname
     *
     * @return the value of routeinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getEndstationname() {
        return endstationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeinfo.endstationname
     *
     * @param endstationname the value for routeinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setEndstationname(String endstationname) {
        this.endstationname = endstationname == null ? null : endstationname.trim();
    }
}