package kevin.tm.dao.model;

import java.util.Date;

public class RouteScheduleBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer scheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer schedulerouteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.schedulename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String schedulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer schedulebusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.starttime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routeschedule.endtime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.scheduleid
     *
     * @return the value of routeschedule.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getScheduleid() {
        return scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.scheduleid
     *
     * @param scheduleid the value for routeschedule.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setScheduleid(Integer scheduleid) {
        this.scheduleid = scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.schedulerouteid
     *
     * @return the value of routeschedule.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getSchedulerouteid() {
        return schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.schedulerouteid
     *
     * @param schedulerouteid the value for routeschedule.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setSchedulerouteid(Integer schedulerouteid) {
        this.schedulerouteid = schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.schedulename
     *
     * @return the value of routeschedule.schedulename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getSchedulename() {
        return schedulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.schedulename
     *
     * @param schedulename the value for routeschedule.schedulename
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setSchedulename(String schedulename) {
        this.schedulename = schedulename == null ? null : schedulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.schedulebusid
     *
     * @return the value of routeschedule.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getSchedulebusid() {
        return schedulebusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.schedulebusid
     *
     * @param schedulebusid the value for routeschedule.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setSchedulebusid(Integer schedulebusid) {
        this.schedulebusid = schedulebusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.starttime
     *
     * @return the value of routeschedule.starttime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.starttime
     *
     * @param starttime the value for routeschedule.starttime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routeschedule.endtime
     *
     * @return the value of routeschedule.endtime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routeschedule.endtime
     *
     * @param endtime the value for routeschedule.endtime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}