package kevin.tm.dao.model;

import java.util.Date;

public class Scheduleinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer scheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer schedulerouteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.schedulename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String schedulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Integer schedulebusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.starttime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.endtime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String routename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String startstationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String endstationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String vehicleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduleinfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    private String drivername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.scheduleid
     *
     * @return the value of scheduleinfo.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getScheduleid() {
        return scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.scheduleid
     *
     * @param scheduleid the value for scheduleinfo.scheduleid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setScheduleid(Integer scheduleid) {
        this.scheduleid = scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.schedulerouteid
     *
     * @return the value of scheduleinfo.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getSchedulerouteid() {
        return schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.schedulerouteid
     *
     * @param schedulerouteid the value for scheduleinfo.schedulerouteid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setSchedulerouteid(Integer schedulerouteid) {
        this.schedulerouteid = schedulerouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.schedulename
     *
     * @return the value of scheduleinfo.schedulename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getSchedulename() {
        return schedulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.schedulename
     *
     * @param schedulename the value for scheduleinfo.schedulename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setSchedulename(String schedulename) {
        this.schedulename = schedulename == null ? null : schedulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.schedulebusid
     *
     * @return the value of scheduleinfo.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Integer getSchedulebusid() {
        return schedulebusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.schedulebusid
     *
     * @param schedulebusid the value for scheduleinfo.schedulebusid
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setSchedulebusid(Integer schedulebusid) {
        this.schedulebusid = schedulebusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.starttime
     *
     * @return the value of scheduleinfo.starttime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.starttime
     *
     * @param starttime the value for scheduleinfo.starttime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.endtime
     *
     * @return the value of scheduleinfo.endtime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.endtime
     *
     * @param endtime the value for scheduleinfo.endtime
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.routename
     *
     * @return the value of scheduleinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.routename
     *
     * @param routename the value for scheduleinfo.routename
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.startstationname
     *
     * @return the value of scheduleinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getStartstationname() {
        return startstationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.startstationname
     *
     * @param startstationname the value for scheduleinfo.startstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setStartstationname(String startstationname) {
        this.startstationname = startstationname == null ? null : startstationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.endstationname
     *
     * @return the value of scheduleinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getEndstationname() {
        return endstationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.endstationname
     *
     * @param endstationname the value for scheduleinfo.endstationname
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setEndstationname(String endstationname) {
        this.endstationname = endstationname == null ? null : endstationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.vehicleno
     *
     * @return the value of scheduleinfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getVehicleno() {
        return vehicleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.vehicleno
     *
     * @param vehicleno the value for scheduleinfo.vehicleno
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setVehicleno(String vehicleno) {
        this.vehicleno = vehicleno == null ? null : vehicleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduleinfo.drivername
     *
     * @return the value of scheduleinfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getDrivername() {
        return drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduleinfo.drivername
     *
     * @param drivername the value for scheduleinfo.drivername
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setDrivername(String drivername) {
        this.drivername = drivername == null ? null : drivername.trim();
    }
}