package kevin.tm.dao.model;

public class StationBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.stationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.stationname
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.locationx
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Double locationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.locationy
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Double locationy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.stationid
     *
     * @return the value of station.stationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.stationid
     *
     * @param stationid the value for station.stationid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setStationid(Integer stationid) {
        this.stationid = stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.stationname
     *
     * @return the value of station.stationname
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.stationname
     *
     * @param stationname the value for station.stationname
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.locationx
     *
     * @return the value of station.locationx
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Double getLocationx() {
        return locationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.locationx
     *
     * @param locationx the value for station.locationx
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setLocationx(Double locationx) {
        this.locationx = locationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.locationy
     *
     * @return the value of station.locationy
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Double getLocationy() {
        return locationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.locationy
     *
     * @param locationy the value for station.locationy
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setLocationy(Double locationy) {
        this.locationy = locationy;
    }
}