package kevin.tm.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TicketinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public TicketinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTicketidIsNull() {
            addCriterion("ticketid is null");
            return (Criteria) this;
        }

        public Criteria andTicketidIsNotNull() {
            addCriterion("ticketid is not null");
            return (Criteria) this;
        }

        public Criteria andTicketidEqualTo(Integer value) {
            addCriterion("ticketid =", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidNotEqualTo(Integer value) {
            addCriterion("ticketid <>", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidGreaterThan(Integer value) {
            addCriterion("ticketid >", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticketid >=", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidLessThan(Integer value) {
            addCriterion("ticketid <", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidLessThanOrEqualTo(Integer value) {
            addCriterion("ticketid <=", value, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidIn(List<Integer> values) {
            addCriterion("ticketid in", values, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidNotIn(List<Integer> values) {
            addCriterion("ticketid not in", values, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidBetween(Integer value1, Integer value2) {
            addCriterion("ticketid between", value1, value2, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketidNotBetween(Integer value1, Integer value2) {
            addCriterion("ticketid not between", value1, value2, "ticketid");
            return (Criteria) this;
        }

        public Criteria andTicketnoIsNull() {
            addCriterion("ticketno is null");
            return (Criteria) this;
        }

        public Criteria andTicketnoIsNotNull() {
            addCriterion("ticketno is not null");
            return (Criteria) this;
        }

        public Criteria andTicketnoEqualTo(String value) {
            addCriterion("ticketno =", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoNotEqualTo(String value) {
            addCriterion("ticketno <>", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoGreaterThan(String value) {
            addCriterion("ticketno >", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoGreaterThanOrEqualTo(String value) {
            addCriterion("ticketno >=", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoLessThan(String value) {
            addCriterion("ticketno <", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoLessThanOrEqualTo(String value) {
            addCriterion("ticketno <=", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoLike(String value) {
            addCriterion("ticketno like", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoNotLike(String value) {
            addCriterion("ticketno not like", value, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoIn(List<String> values) {
            addCriterion("ticketno in", values, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoNotIn(List<String> values) {
            addCriterion("ticketno not in", values, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoBetween(String value1, String value2) {
            addCriterion("ticketno between", value1, value2, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTicketnoNotBetween(String value1, String value2) {
            addCriterion("ticketno not between", value1, value2, "ticketno");
            return (Criteria) this;
        }

        public Criteria andTickettitleIsNull() {
            addCriterion("tickettitle is null");
            return (Criteria) this;
        }

        public Criteria andTickettitleIsNotNull() {
            addCriterion("tickettitle is not null");
            return (Criteria) this;
        }

        public Criteria andTickettitleEqualTo(String value) {
            addCriterion("tickettitle =", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleNotEqualTo(String value) {
            addCriterion("tickettitle <>", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleGreaterThan(String value) {
            addCriterion("tickettitle >", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleGreaterThanOrEqualTo(String value) {
            addCriterion("tickettitle >=", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleLessThan(String value) {
            addCriterion("tickettitle <", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleLessThanOrEqualTo(String value) {
            addCriterion("tickettitle <=", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleLike(String value) {
            addCriterion("tickettitle like", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleNotLike(String value) {
            addCriterion("tickettitle not like", value, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleIn(List<String> values) {
            addCriterion("tickettitle in", values, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleNotIn(List<String> values) {
            addCriterion("tickettitle not in", values, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleBetween(String value1, String value2) {
            addCriterion("tickettitle between", value1, value2, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTickettitleNotBetween(String value1, String value2) {
            addCriterion("tickettitle not between", value1, value2, "tickettitle");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidIsNull() {
            addCriterion("ticketscheduleid is null");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidIsNotNull() {
            addCriterion("ticketscheduleid is not null");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidEqualTo(Integer value) {
            addCriterion("ticketscheduleid =", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidNotEqualTo(Integer value) {
            addCriterion("ticketscheduleid <>", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidGreaterThan(Integer value) {
            addCriterion("ticketscheduleid >", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticketscheduleid >=", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidLessThan(Integer value) {
            addCriterion("ticketscheduleid <", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidLessThanOrEqualTo(Integer value) {
            addCriterion("ticketscheduleid <=", value, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidIn(List<Integer> values) {
            addCriterion("ticketscheduleid in", values, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidNotIn(List<Integer> values) {
            addCriterion("ticketscheduleid not in", values, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidBetween(Integer value1, Integer value2) {
            addCriterion("ticketscheduleid between", value1, value2, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andTicketscheduleidNotBetween(Integer value1, Integer value2) {
            addCriterion("ticketscheduleid not between", value1, value2, "ticketscheduleid");
            return (Criteria) this;
        }

        public Criteria andSeatnoIsNull() {
            addCriterion("seatno is null");
            return (Criteria) this;
        }

        public Criteria andSeatnoIsNotNull() {
            addCriterion("seatno is not null");
            return (Criteria) this;
        }

        public Criteria andSeatnoEqualTo(String value) {
            addCriterion("seatno =", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoNotEqualTo(String value) {
            addCriterion("seatno <>", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoGreaterThan(String value) {
            addCriterion("seatno >", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoGreaterThanOrEqualTo(String value) {
            addCriterion("seatno >=", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoLessThan(String value) {
            addCriterion("seatno <", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoLessThanOrEqualTo(String value) {
            addCriterion("seatno <=", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoLike(String value) {
            addCriterion("seatno like", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoNotLike(String value) {
            addCriterion("seatno not like", value, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoIn(List<String> values) {
            addCriterion("seatno in", values, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoNotIn(List<String> values) {
            addCriterion("seatno not in", values, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoBetween(String value1, String value2) {
            addCriterion("seatno between", value1, value2, "seatno");
            return (Criteria) this;
        }

        public Criteria andSeatnoNotBetween(String value1, String value2) {
            addCriterion("seatno not between", value1, value2, "seatno");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("customername is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("customername is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("customername =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("customername <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("customername >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("customername >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("customername <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("customername <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("customername like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("customername not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("customername in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("customername not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("customername between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("customername not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNull() {
            addCriterion("entrytime is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNotNull() {
            addCriterion("entrytime is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeEqualTo(Date value) {
            addCriterion("entrytime =", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotEqualTo(Date value) {
            addCriterion("entrytime <>", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThan(Date value) {
            addCriterion("entrytime >", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("entrytime >=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThan(Date value) {
            addCriterion("entrytime <", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThanOrEqualTo(Date value) {
            addCriterion("entrytime <=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIn(List<Date> values) {
            addCriterion("entrytime in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotIn(List<Date> values) {
            addCriterion("entrytime not in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeBetween(Date value1, Date value2) {
            addCriterion("entrytime between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotBetween(Date value1, Date value2) {
            addCriterion("entrytime not between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(Date value) {
            addCriterion("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(Date value) {
            addCriterion("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(Date value) {
            addCriterion("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(Date value) {
            addCriterion("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<Date> values) {
            addCriterion("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<Date> values) {
            addCriterion("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(Date value1, Date value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andCheckedIsNull() {
            addCriterion("checked is null");
            return (Criteria) this;
        }

        public Criteria andCheckedIsNotNull() {
            addCriterion("checked is not null");
            return (Criteria) this;
        }

        public Criteria andCheckedEqualTo(Boolean value) {
            addCriterion("checked =", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotEqualTo(Boolean value) {
            addCriterion("checked <>", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedGreaterThan(Boolean value) {
            addCriterion("checked >", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("checked >=", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedLessThan(Boolean value) {
            addCriterion("checked <", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedLessThanOrEqualTo(Boolean value) {
            addCriterion("checked <=", value, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedIn(List<Boolean> values) {
            addCriterion("checked in", values, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotIn(List<Boolean> values) {
            addCriterion("checked not in", values, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedBetween(Boolean value1, Boolean value2) {
            addCriterion("checked between", value1, value2, "checked");
            return (Criteria) this;
        }

        public Criteria andCheckedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("checked not between", value1, value2, "checked");
            return (Criteria) this;
        }

        public Criteria andSchedulenameIsNull() {
            addCriterion("schedulename is null");
            return (Criteria) this;
        }

        public Criteria andSchedulenameIsNotNull() {
            addCriterion("schedulename is not null");
            return (Criteria) this;
        }

        public Criteria andSchedulenameEqualTo(String value) {
            addCriterion("schedulename =", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameNotEqualTo(String value) {
            addCriterion("schedulename <>", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameGreaterThan(String value) {
            addCriterion("schedulename >", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameGreaterThanOrEqualTo(String value) {
            addCriterion("schedulename >=", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameLessThan(String value) {
            addCriterion("schedulename <", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameLessThanOrEqualTo(String value) {
            addCriterion("schedulename <=", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameLike(String value) {
            addCriterion("schedulename like", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameNotLike(String value) {
            addCriterion("schedulename not like", value, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameIn(List<String> values) {
            addCriterion("schedulename in", values, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameNotIn(List<String> values) {
            addCriterion("schedulename not in", values, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameBetween(String value1, String value2) {
            addCriterion("schedulename between", value1, value2, "schedulename");
            return (Criteria) this;
        }

        public Criteria andSchedulenameNotBetween(String value1, String value2) {
            addCriterion("schedulename not between", value1, value2, "schedulename");
            return (Criteria) this;
        }

        public Criteria andRoutenameIsNull() {
            addCriterion("routename is null");
            return (Criteria) this;
        }

        public Criteria andRoutenameIsNotNull() {
            addCriterion("routename is not null");
            return (Criteria) this;
        }

        public Criteria andRoutenameEqualTo(String value) {
            addCriterion("routename =", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameNotEqualTo(String value) {
            addCriterion("routename <>", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameGreaterThan(String value) {
            addCriterion("routename >", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameGreaterThanOrEqualTo(String value) {
            addCriterion("routename >=", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameLessThan(String value) {
            addCriterion("routename <", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameLessThanOrEqualTo(String value) {
            addCriterion("routename <=", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameLike(String value) {
            addCriterion("routename like", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameNotLike(String value) {
            addCriterion("routename not like", value, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameIn(List<String> values) {
            addCriterion("routename in", values, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameNotIn(List<String> values) {
            addCriterion("routename not in", values, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameBetween(String value1, String value2) {
            addCriterion("routename between", value1, value2, "routename");
            return (Criteria) this;
        }

        public Criteria andRoutenameNotBetween(String value1, String value2) {
            addCriterion("routename not between", value1, value2, "routename");
            return (Criteria) this;
        }

        public Criteria andStartstationnameIsNull() {
            addCriterion("startstationname is null");
            return (Criteria) this;
        }

        public Criteria andStartstationnameIsNotNull() {
            addCriterion("startstationname is not null");
            return (Criteria) this;
        }

        public Criteria andStartstationnameEqualTo(String value) {
            addCriterion("startstationname =", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameNotEqualTo(String value) {
            addCriterion("startstationname <>", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameGreaterThan(String value) {
            addCriterion("startstationname >", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameGreaterThanOrEqualTo(String value) {
            addCriterion("startstationname >=", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameLessThan(String value) {
            addCriterion("startstationname <", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameLessThanOrEqualTo(String value) {
            addCriterion("startstationname <=", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameLike(String value) {
            addCriterion("startstationname like", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameNotLike(String value) {
            addCriterion("startstationname not like", value, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameIn(List<String> values) {
            addCriterion("startstationname in", values, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameNotIn(List<String> values) {
            addCriterion("startstationname not in", values, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameBetween(String value1, String value2) {
            addCriterion("startstationname between", value1, value2, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStartstationnameNotBetween(String value1, String value2) {
            addCriterion("startstationname not between", value1, value2, "startstationname");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("starttime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("starttime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("starttime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("starttime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndstationnameIsNull() {
            addCriterion("endstationname is null");
            return (Criteria) this;
        }

        public Criteria andEndstationnameIsNotNull() {
            addCriterion("endstationname is not null");
            return (Criteria) this;
        }

        public Criteria andEndstationnameEqualTo(String value) {
            addCriterion("endstationname =", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameNotEqualTo(String value) {
            addCriterion("endstationname <>", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameGreaterThan(String value) {
            addCriterion("endstationname >", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameGreaterThanOrEqualTo(String value) {
            addCriterion("endstationname >=", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameLessThan(String value) {
            addCriterion("endstationname <", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameLessThanOrEqualTo(String value) {
            addCriterion("endstationname <=", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameLike(String value) {
            addCriterion("endstationname like", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameNotLike(String value) {
            addCriterion("endstationname not like", value, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameIn(List<String> values) {
            addCriterion("endstationname in", values, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameNotIn(List<String> values) {
            addCriterion("endstationname not in", values, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameBetween(String value1, String value2) {
            addCriterion("endstationname between", value1, value2, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndstationnameNotBetween(String value1, String value2) {
            addCriterion("endstationname not between", value1, value2, "endstationname");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andVehiclenoIsNull() {
            addCriterion("vehicleno is null");
            return (Criteria) this;
        }

        public Criteria andVehiclenoIsNotNull() {
            addCriterion("vehicleno is not null");
            return (Criteria) this;
        }

        public Criteria andVehiclenoEqualTo(String value) {
            addCriterion("vehicleno =", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotEqualTo(String value) {
            addCriterion("vehicleno <>", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoGreaterThan(String value) {
            addCriterion("vehicleno >", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoGreaterThanOrEqualTo(String value) {
            addCriterion("vehicleno >=", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLessThan(String value) {
            addCriterion("vehicleno <", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLessThanOrEqualTo(String value) {
            addCriterion("vehicleno <=", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLike(String value) {
            addCriterion("vehicleno like", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotLike(String value) {
            addCriterion("vehicleno not like", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoIn(List<String> values) {
            addCriterion("vehicleno in", values, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotIn(List<String> values) {
            addCriterion("vehicleno not in", values, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoBetween(String value1, String value2) {
            addCriterion("vehicleno between", value1, value2, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotBetween(String value1, String value2) {
            addCriterion("vehicleno not between", value1, value2, "vehicleno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticketinfo
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 11 14:47:47 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticketinfo
     *
     * @mbggenerated Tue Mar 11 14:47:47 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}