package kevin.tm.dao.model;

import java.util.Date;

public class TicketBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticketid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer ticketid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticketno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String ticketno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.tickettitle
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String tickettitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticketscheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Integer ticketscheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seatno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String seatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.customername
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.entrytime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Date entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.deadline
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.checked
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    private Boolean checked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticketid
     *
     * @return the value of ticket.ticketid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getTicketid() {
        return ticketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticketid
     *
     * @param ticketid the value for ticket.ticketid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setTicketid(Integer ticketid) {
        this.ticketid = ticketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticketno
     *
     * @return the value of ticket.ticketno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getTicketno() {
        return ticketno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticketno
     *
     * @param ticketno the value for ticket.ticketno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setTicketno(String ticketno) {
        this.ticketno = ticketno == null ? null : ticketno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.tickettitle
     *
     * @return the value of ticket.tickettitle
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getTickettitle() {
        return tickettitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.tickettitle
     *
     * @param tickettitle the value for ticket.tickettitle
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setTickettitle(String tickettitle) {
        this.tickettitle = tickettitle == null ? null : tickettitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticketscheduleid
     *
     * @return the value of ticket.ticketscheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Integer getTicketscheduleid() {
        return ticketscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticketscheduleid
     *
     * @param ticketscheduleid the value for ticket.ticketscheduleid
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setTicketscheduleid(Integer ticketscheduleid) {
        this.ticketscheduleid = ticketscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seatno
     *
     * @return the value of ticket.seatno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getSeatno() {
        return seatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seatno
     *
     * @param seatno the value for ticket.seatno
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setSeatno(String seatno) {
        this.seatno = seatno == null ? null : seatno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.customername
     *
     * @return the value of ticket.customername
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.customername
     *
     * @param customername the value for ticket.customername
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.entrytime
     *
     * @return the value of ticket.entrytime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.entrytime
     *
     * @param entrytime the value for ticket.entrytime
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.deadline
     *
     * @return the value of ticket.deadline
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.deadline
     *
     * @param deadline the value for ticket.deadline
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.checked
     *
     * @return the value of ticket.checked
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.checked
     *
     * @param checked the value for ticket.checked
     *
     * @mbggenerated Tue Mar 11 14:14:51 CST 2014
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }
}